### ISSUE TITLE
Dawn Segfault, 4 AP configuration

### ISSUE THREAD

**Issue by morhimi** [berlin-open-wireless-lab/DAWN#117]
I have 4 AP configured with latest version of Dawn (August 7 IIRC), latest master snapshot as of August 13.
Dawn crashes sporadically:

kern.info kernel: [41490.149494] do_page_fault(): sending SIGSEGV to dawn for invalid write access to 00000000
kern.info kernel: [41490.157830] epc = 77e56f50 in libc.so[77e29000+9c000]
kern.info kernel: [41490.162966] ra  = 77db55b1 in libuci.so[77db4000+16000]
daemon.err uhttpd[1475]: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
daemon.err uhttpd[1475]: A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template '[string]'.
daemon.err uhttpd[1475]: A runtime error occurred: [string "[string]"]:8: bad argument #1 to 'pairs' (table expected, got nil)
daemon.err uhttpd[1475]: stack traceback:
daemon.err uhttpd[1475]: 	[C]: in function 'pairs'
daemon.err uhttpd[1475]: 	[string "[string]"]:8: in main chunk
daemon.err uhttpd[1475]: stack traceback:
daemon.err uhttpd[1475]: 	[C]: in function 'error'
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
daemon.err uhttpd[1475]: 	(tail call): ?
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/model/cbi/dawn/dawn_network.lua:10: in function 'render'
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/cbi.lua:266: in function 'render_children'
daemon.err uhttpd[1475]: 	[string "/usr/lib/lua/luci/view/cbi/map.htm"]:6: in main chunk
daemon.err uhttpd[1475]: stack traceback:
daemon.err uhttpd[1475]: 	[C]: in function 'error'
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
daemon.err uhttpd[1475]: 	(tail call): ?
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/cbi.lua:440: in function 'render'
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/dispatcher.lua:1451: in function '_cbi'
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/dispatcher.lua:1024: in function 'dispatch'
daemon.err uhttpd[1475]: 	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>
daemon.err uhttpd[1475]: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.

**Comment by babarosaM33** [comment]
try to keep  one ap with luci-dawn-app installed.

two ap setup of mine is working well for 4 days.

**Comment by morhimi** [comment]
@PolynomialDivision I think this issue can be closed, with the latest DAWN there are no crashes in the last few days
