### ISSUE TITLE
dawn causes problems

### ISSUE THREAD

**Issue by WiredLife** [berlin-open-wireless-lab/DAWN#118]
hello, i have dawn running on a few tp-link ap's (wdr36000, wdr43000, archer c7) all with SNAPSHOT r14165-ff6b815691
and after some time dawn is crashing on some of them and the others becoming problems with the error
Sun Aug 16 13:00:19 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:00:33 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:00:48 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:01:03 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:01:19 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:01:35 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:01:51 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:02:07 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:02:24 2020 daemon.err dawn[1363]: Connection failed (ERROR)
Sun Aug 16 13:02:41 2020 daemon.err dawn[1363]: Connection failed (ERROR)
its repeating endlessly

on some i got this here
Sun Aug 16 11:31:06 2020 daemon.err dawn[5004]: eof!, pending: 0, total: 132098
Sun Aug 16 11:31:06 2020 daemon.err dawn[5004]: Connection to server closed
Sun Aug 16 11:31:06 2020 daemon.err dawn[5004]: eof!, pending: 0, total: 0
Sun Aug 16 11:31:06 2020 daemon.err dawn[5004]: Connection closed
Sun Aug 16 11:31:53 2020 daemon.err dawn[5004]: Connection established
Sun Aug 16 11:32:10 2020 daemon.err dawn[5004]: New connection
Sun Aug 16 11:34:40 2020 daemon.err dawn[5004]: eof!, pending: 0, total: 0
Sun Aug 16 11:34:40 2020 daemon.err dawn[5004]: Connection closed
Sun Aug 16 11:34:40 2020 daemon.err dawn[5004]: eof!, pending: 0, total: 132098
Sun Aug 16 11:34:40 2020 daemon.err dawn[5004]: Connection to server closed
Sun Aug 16 11:35:26 2020 daemon.err dawn[5004]: Connection established
Sun Aug 16 11:35:31 2020 daemon.err dawn[5004]: eof!, pending: 0, total: 132098
Sun Aug 16 11:35:31 2020 daemon.err dawn[5004]: Connection to server closed
Sun Aug 16 11:35:31 2020 daemon.err dawn[5004]: eof!, pending: 0, total: 0
Sun Aug 16 11:35:31 2020 daemon.err dawn[5004]: Connection closed
Sun Aug 16 11:35:40 2020 daemon.err dawn[5004]: New connection
Sun Aug 16 11:35:41 2020 daemon.err dawn[5004]: Connection failed (ERROR)

this on one where dawn has crashed
Sun Aug 16 11:31:10 2020 daemon.err dawn[4777]: Ustream error(339)!
Sun Aug 16 11:31:14 2020 daemon.err dawn[4777]: eof!, pending: 0, total: 0
Sun Aug 16 11:31:14 2020 daemon.err dawn[4777]: Connection closed
Sun Aug 16 11:31:58 2020 daemon.err dawn[4777]: Connection established
Sun Aug 16 11:32:00 2020 daemon.err dawn[4777]: New connection
Sun Aug 16 11:32:21 2020 daemon.err dawn[4777]: Connection established
Sun Aug 16 11:34:41 2020 daemon.err dawn[4777]: Ustream error(339)!
Sun Aug 16 11:34:41 2020 daemon.err dawn[4777]: eof!, pending: 0, total: 0
Sun Aug 16 11:34:41 2020 daemon.err dawn[4777]: Connection closed
Sun Aug 16 11:35:31 2020 daemon.err dawn[4777]: Connection failed (ERROR)
Sun Aug 16 11:35:31 2020 kern.info kernel: [210363.522444] do_page_fault(): sending SIGSEGV to dawn for invalid write access to 00000004
Sun Aug 16 11:35:31 2020 kern.info kernel: [210363.531162] epc = 00407b35 in dawn[400000+c000]
Sun Aug 16 11:35:31 2020 kern.info kernel: [210363.535991] ra  = 00407f01 in dawn[400000+c000]

i have not configured dawn, so i'm using the defaults
maybe you can help me to fix that

**Comment by PolynomialDivision** [comment]
I will close this issue since I don't receive any new information. I think this bug should be fixed with the new version.
Feel free to open this issue again if the bug still exists.
