### ISSUE TITLE
"Network Overview" and "Hearing Map" issues

### ISSUE THREAD

**Issue by XiaoliChan** [berlin-open-wireless-lab/DAWN#120]
"Network Overview" did not sync in each AP

> AP in room1
> <a><img src="https://i.loli.net/2020/08/22/gFX4UWBxbECAPeI.png" ></a>
> AP in living room
> <a><img src="https://i.loli.net/2020/08/22/cyq1OE2stmebUY6.png" ></a>

"Hearing Map" still bugly, hope fix and improve it soon.(It did not sync each AP also)

> AP in room1
> <a><img src="https://i.loli.net/2020/08/22/F5HZYxd9rsiDSQ6.png" ></a>
> AP in living room
> <a><img src="https://i.loli.net/2020/08/22/QZ9LVCR6eI8qhfz.png" ></a>

> #113

**Comment by PolynomialDivision** [comment]
>  Yes, I mean the signal strength seen did not synced.

I have to reproduce that. So u did the the screenshots simultaneously?

**Comment by XiaoliChan** [comment]
> I have to reproduce that. So u did the the screenshots simultaneously?

Yes, I did the screenshots at same time.
I also try to reflash the web page many times, but the signal part seen still did not synced.

**Comment by PolynomialDivision** [comment]
>  I also try to reflash the web page many times, but the signal part seen still did not synced.

Okay, that is really weird. This is wrong. Even If u look in the hearing map and the network overview, the RSSI is not synced. We currently refactored all that database handling and maybe we there is some failure.

**Comment by PolynomialDivision** [comment]
@Ian-Clowes 

Not sure who added this, but maybe there is something wrong here: https://github.com/berlin-open-wireless-lab/DAWN/blob/master/src/utils/ubus.c#L1524-L1532

We release the mutex to early?

**Comment by XiaoliChan** [comment]
The another issue is the Kick function seen lazy to kick client even I set `min_number_to_kick '0'` and `bandwidth_threshold '2147483647'`

**Comment by PolynomialDivision** [comment]
> The another issue is the Kick function seen lazy to kick client even I set `min_number_to_kick '0'` and `bandwidth_threshold '2147483647'`

Try setting `min_number_to_kick` to `0`.

**Comment by XiaoliChan** [comment]
> Try setting `min_number_to_kick` to `0`.

I already set it :)

**Comment by PolynomialDivision** [comment]
> Not sure who added this, but maybe there is something wrong here: https://github.com/berlin-open-wireless-lab/DAWN/blob/master/src/utils/ubus.c#L1524-L1532

Sry, we are handling with pointer now directly to the allocated probe entry.

I will have a look if I spot some error. ;)

**Comment by morhimi** [comment]
I can confirm that signal strength doesn't sync and seem stuck often.
Let me know if I can assist with debugging it (logs etc..)

**Comment by PolynomialDivision** [comment]
I think here is a mistake:
https://github.com/berlin-open-wireless-lab/DAWN/blob/master/src/utils/ubus.c#L483-L489

A new probe and an old probe are not equivalent.

**Comment by PolynomialDivision** [comment]
Here is the PR that should fix the issues: https://github.com/berlin-open-wireless-lab/DAWN/pull/121

**Comment by XiaoliChan** [comment]
> Here is the PR that should fix the issues: #121

Okay, I will test it when PR is pass.

**Comment by PolynomialDivision** [comment]
> > Here is the PR that should fix the issues: #121
> 
> Okay, I will test it when PR is pass.

BTW: Thanks for testing and reporting! This issue could destroy all steering logic... :)

If u say it works, I would merge it to master and update the package feed.
