### ISSUE TITLE
Luci - Network Overview and Hearing Map crashed with openwrt-2020 theme

### ISSUE THREAD

**Issue by XiaoliChan** [berlin-open-wireless-lab/DAWN#132]
Screenshots: 
![微信截图_20210302165122](https://user-images.githubusercontent.com/30458572/109622973-a84ee700-7b77-11eb-9810-db985f590f2a.png)
![微信截图_20210302165132](https://user-images.githubusercontent.com/30458572/109622989-ac7b0480-7b77-11eb-923e-e0cdf652e8ca.png)

**Comment by PolynomialDivision** [comment]
Could u give the console output of your browser?

**Comment by XiaoliChan** [comment]
> Could u give the console output of your browser?

I already save the page as a static page.

[Network Overview page](https://drive.google.com/file/d/1-0u_6IP8Sjf-vhEUDBc29EKT3o9FMyyB/view?usp=sharing)
[Hearing Map page](https://drive.google.com/file/d/1eL3zk4xvkkjvFQng1NriUSFUlx-HcpKE/view?usp=sharing)

**Comment by XiaoliChan** [comment]
I have no idea what happened on Luci interface, but it seen has been fixed.
