### ISSUE TITLE
DAWN: multiple issues

### ISSUE THREAD

**Issue by XiaoliChan** [berlin-open-wireless-lab/DAWN#149]
Device: Newifi-d1 x3
Device wireless chipset: mt7612e + mt7603e

## First issue:
It seen something wrong on DAWN and make it can't "talk" with each AP
![image](https://user-images.githubusercontent.com/30458572/135761933-2990f6e1-be6d-48f4-9c2f-691f11426c30.png)
![image](https://user-images.githubusercontent.com/30458572/135761956-b139c777-e692-4f0b-a3c8-c2a99194eedf.png)

Ubus result
![image](https://user-images.githubusercontent.com/30458572/135762091-8e41d1b6-6032-4622-9774-b8aae45bf164.png)

But in the system log, It said the connection failed
![image](https://user-images.githubusercontent.com/30458572/135762229-531ad6c6-5ed1-4ed2-b308-323952622c7c.png)

Make sure I have already disabled the firewall
![image](https://user-images.githubusercontent.com/30458572/135762259-bfb472e4-d057-4a8a-8eab-46f39fabee83.png)

## Second issue:
Same as issue: [#16777](https://github.com/openwrt/packages/issues/16777)

Seems when DAWN crashed, DAWN's Luci interface also be crashed.

## Last:
I have already tested the latest version of DAWN, after this commit 6eb747b4d4d86902ed7394bd6aaa9e957686d5e0, DAWN's Luci app needs to be updated because 802.11a and 802.11g configure independently. If not, DAWN's Luci configuration page will show in a weird way.

**Comment by PolynomialDivision** [comment]
And? ;)
