### ISSUE TITLE
after dawn upgrade, APs don't see each other

### ISSUE THREAD

**Issue by morhimi** [berlin-open-wireless-lab/DAWN#153]
I have 4 APs
all running latest master snapshot as of yesterday morning, and latest dawn
```root@OpenWrt_RM2100_LVR:~# opkg list | grep dawn
dawn - 2021-10-13-7f1cb854-1
luci-app-dawn - git-21.282.29102-4a78122
```
after the upgrade, all APs only see each other, there is no firewall and all on the same subnet and configured as Dumb AP.
any help would be appreciated

My config (on all 4):

> root@OpenWrt_RM2100_LVR:~# cat /etc/config/dawn
> 
> config network
> 	option broadcast_port '1025'
> 	option tcp_port '1026'
> 	option network_option '2'
> 	option shared_key 'Niiiiiiiiiiiiick'
> 	option iv 'Niiiiiiiiiiiiick'
> 	option use_symm_enc '0'
> 	option collision_domain '-1'
> 	option bandwidth '-1'
> 	option broadcast_ip '10.0.0.255'
> 
> config ordering
> 	option sort_order 'cbfs'
> 
> config hostapd
> 	option hostapd_dir '/var/run/hostapd'
> 
> config times
> 	option update_client '10'
> 	option denied_req_threshold '30'
> 	option remove_client '15'
> 	option remove_probe '30'
> 	option remove_ap '460'
> 	option update_hostapd '10'
> 	option update_tcp_con '10'
> 	option update_chan_util '5'
> 	option update_beacon_reports '0'
> 
> config metric 'global'
> 	option rssi_weight '0'
> 	option rssi_center '0'
> 	option initial_score '0'
> 	option kicking_threshold '20'
> 	option duration '600'
> 	option rrm_mode 'apt'
> 	option ap_weight '0'
> 	option ht_support '0'
> 	option vht_support '0'
> 	option no_ht_support '0'
> 	option no_vht_support '0'
> 	option rssi '0'
> 	option low_rssi '0'
> 	option freq '0'
> 	option chan_util '0'
> 	option max_chan_util '0'
> 	option rssi_val '-60'
> 	option low_rssi_val '-80'
> 	option chan_util_val '0'
> 	option max_chan_util_val '0'
> 	option min_probe_count '0'
> 	option bandwidth_threshold '6'
> 	option use_station_count '0'
> 	option max_station_diff '0'
> 	option eval_probe_req '0'
> 	option eval_auth_req '0'
> 	option eval_assoc_req '0'
> 	option kicking '0'
> 	option deny_auth_reason '1'
> 	option deny_assoc_reason '17'
> 	option use_driver_recog '1'
> 	option chan_util_avg_period '3'
> 	option set_hostapd_nr '1'
> 
> config metric '802_11a'
> 	option rssi_weight '2'
> 	option rssi_center '-70'
> 	option initial_score '125'
> 
> config metric '802_11g'
> 	option rssi_weight '2'
> 	option rssi_center '-70'
> 	option initial_score '100'

**Comment by PolynomialDivision** [comment]
Is umdns working and all th dawn announcements?

**Comment by morhimi** [comment]
> Is umdns working and all th dawn announcements?

regarding umdns:
```
root@OpenWrt_RM2100_LVR:~# /etc/init.d/umdns status
running
root@OpenWrt_RM2100_LVR:~# cat /etc/config/umdns
config umdns
	option jail 1
	list network lan
	list network wan
```

How to check Dawn announcements?

**Comment by PolynomialDivision** [comment]
Do you have `procd-ujai` and `procd-seccomp` installed? Please install it if you want to use jail.

**Comment by morhimi** [comment]
I'm experiencing crashes of dawn, I'm closing the issue and will post in the relevant thread
