### ISSUE TITLE
openwrt system log flooded : daemon.warn dawn[2028]: No station connected

### ISSUE THREAD

**Issue by kaikus** [berlin-open-wireless-lab/DAWN#173]
even with 

config local
    option loglevel             '0'

the log file is flooded every 10 seconds with 

Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:15 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected
Thu Jun  9 12:14:25 2022 daemon.warn dawn[2028]: No station connected

**Comment by palfal** [comment]
same is here

**Comment by PolynomialDivision** [comment]
@kaikus You set the debug-level to the lowest. Just set it higher?

**Comment by kaikus** [comment]
What does this mean ? Higher level, less entries in log ?

**Comment by kaikus** [comment]
So it seems this documentation needs to be updated ?

https://github.com/Ian-Clowes/DAWN/blob/master/CONFIGURE.md

**Comment by PolynomialDivision** [comment]
> So it seems this documentation needs to be updated ?
> 
> https://github.com/Ian-Clowes/DAWN/blob/master/CONFIGURE.md

Yep. Thanks for reporting.

**Comment by PolynomialDivision** [comment]
Done
