### ISSUE TITLE
dawn kicking due to low active data transfer: RX rate 6.000000 below 6 limit

### ISSUE THREAD

**Issue by schuettecarsten** [berlin-open-wireless-lab/DAWN#177]
I can see lots of messages like "Kicking due to low active data transfer: RX rate 6.000000 below 6 limit" in the log. Why does dawn kick clients with 6.0000 rate when limit is 6....?

**Comment by PolynomialDivision** [comment]
As written in the code we check for `<=`:
https://github.com/berlin-open-wireless-lab/DAWN/blob/master/src/storage/datastorage.c#L564-L568
