### ISSUE TITLE
Exclude client from management?

### ISSUE THREAD

**Issue by jeff47** [berlin-open-wireless-lab/DAWN#179]
I'm using Dawn in a mixed 2.4/5 GHz network.  I have some clients that can only connect on the 2.4 GHz band.  How can I prevent Dawn from kicking them to the 5 GHz band, while still favoring the 5 GHz band for clients capable of using it?

**Comment by PolynomialDivision** [comment]
Did you experience such behavior? 2.4GHz-Only-Clients should not be able to scan the 5 GHz band (neither probing nor 802.11k). So no entry for the 5 GHz band should exist, and that is why DAWN should not try to kick them to the 5 GHz band.

**Comment by PolynomialDivision** [comment]
Did you experience such behavior? 2.4GHz-Only-Clients should not be able to scan the 5 GHz band (neither probing nor 802.11k). So no entry for the 5 GHz band should exist, and that is why DAWN should not try to kick them to the 5 GHz band.

**Comment by jeff47** [comment]
Perhaps should have rephrased this to be "is this a concern"?  Apparently it's not!
