### ISSUE TITLE
ap_array_unlink_entry() return always NULL?

### ISSUE THREAD

**Issue by ptpt52** [berlin-open-wireless-lab/DAWN#187]
https://github.com/berlin-open-wireless-lab/DAWN/blob/e596ff131735821684f7ecea73d7634733319f94/src/storage/datastorage.c#L1003-L1011

here why always return (entry = NULL)

@PolynomialDivision @Ian-Clowes

**Comment by PolynomialDivision** [comment]
Thanks for spotting this. Seems like we introduce a lot of memory leaks with that, e.g.
````
dawn_free(ap_array_unlink_entry(i));
```

**Comment by PolynomialDivision** [comment]
@ptpt52 Do you want to add a PR or should I fix it?

**Comment by ptpt52** [comment]
@PolynomialDivision  please fix it.

**Comment by ptpt52** [comment]
fixed in https://github.com/berlin-open-wireless-lab/DAWN/commit/bb362db2facd8ce7a39c430a353b6413ec24d70d
