### ISSUE TITLE
[broadcast mode] Symmetric encryption is broken

### ISSUE THREAD

**Issue by rany2** [berlin-open-wireless-lab/DAWN#219]
Fails with a cannot bind address message.

**Comment by PolynomialDivision** [comment]
Can you give me more output? And your DAWN config?

**Comment by rany2** [comment]
@PolynomialDivision Doesn't crash anymore, I think that when I updated to master to test my changes for https://github.com/berlin-open-wireless-lab/DAWN/pull/220 it fixed itself.
