### ISSUE TITLE
"Hearing Map" and "Network Overview" files in /etc/config

### ISSUE THREAD

**Issue by dengqf6** [berlin-open-wireless-lab/DAWN#64]
After I installed DAWN, it creates 2 empty files named "Hearing Map" and "Network Overview" in `/etc/config`, what are they for?

**Comment by PolynomialDivision** [comment]
The files are coming from the `luci-app-dawn`. I have no idea from luci and just used template file to create the luci app. I have to look which option enables that. This is a bug. 
Thanks for reporting. :)

**Comment by PolynomialDivision** [comment]
Fixed.
