### ISSUE TITLE
memory leak: should call blob_buf_free() after calling blob_buf_init()

### ISSUE THREAD

**Issue by babarosaM33** [berlin-open-wireless-lab/DAWN#85]
every  blob_buf_init in  src/utils/ubus.c is not followed by blob_buf_free.

according to https://lxr.openwrt.org/source/libubox/blob.c#L89

 88 int
 89 blob_buf_init(struct blob_buf *buf, int id)
 90 {
 91         if (!buf->grow)
 92                 buf->grow = blob_buffer_grow;
 93 
 94         buf->head = buf->buf;
 95         if (blob_add(buf, buf->buf, id, 0) == NULL)
 96                 return -ENOMEM;
 97 
 98         return 0;
 99 }
and
101 void
102 blob_buf_free(struct blob_buf *buf)
103 {
104         free(buf->buf);
105         buf->buf = NULL;
106         buf->buflen = 0;
107 }
blob_buf_init did not reset structure before setup.

as a result, dawn might have serious memory leak.

**Comment by babarosaM33** [comment]
issue #79 might be relative with such bug

**Comment by babarosaM33** [comment]
maybe I need dig in deeper about the usage of  blob_buf_init

**Comment by PolynomialDivision** [comment]
I think u are right? :S Let the issue open, I will have a look at this.

**Comment by PolynomialDivision** [comment]
https://forum.openwrt.org/t/should-you-call-blob-buf-free-after-calling-blob-buf-init/65388

**Comment by jonozzz** [comment]
I'm seeing a constant memory increase and this only for a couple of hours:

![46fa0ce6-33bf-47ec-8c3b-96167d539ea7](https://user-images.githubusercontent.com/250343/84705553-6fe77a00-af10-11ea-93ed-ed16a7c668d2.png)

**Comment by PolynomialDivision** [comment]
`blob_buf_init` frees previous memory! :)
