### ISSUE TITLE
Network packet format is host-dependent.

### ISSUE THREAD

**Issue by dwmw2** [berlin-open-wireless-lab/DAWN#92]
I set up DAWN on a couple APs on my local network, but they don't see each other's data. Logs show:
```
Mon Jun  8 10:49:12 2020 daemon.err dawn[19742]: not complete msg, len:308, expected len:872480768
Mon Jun  8 10:49:12 2020 daemon.err dawn[19742]: not complete msg, len:708, expected len:3288465408
```

I note 872480768 is 0x34010000 while 308 is 0x134. The hosts are expecting the network traffic to be in their own endianness. Looking at the code I see it's worse than that; even the *size* of this variable is host-dependent as it's a size_t not a fixed-size type.

**Comment by babarosaM33** [comment]
ah, my mistake.
